services:
  db:
    image: postgres
    container_name: InTempo-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=InTempo
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: InTempo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "15432:80"
    depends_on:
      - db

