spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/InTempo
    username: admin
    password: admin123
    hikari:
      auto-commit: false

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB

  security:
    keys:
      public: classpath:app.pub
      private: classpath:app.key

---
#Produção

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/InTempo